---
- name: "{{ item.name }}"
  parted: 
   device: /dev/sdc
   number: "{{ item.number }}"
   state: present
   part_start: "{{ item.part_start }}"
   part_end: "{{ item.part_end }}"
  loop: "{{ listcreatepartition }}"

- name: "{{ item.name }}"
  filesystem:
   fstype: "{{ item.fstype }}"
   dev: "{{ item.src }}"
  loop: "{{ listmountpartition }}"

- name: "{{ item.name }}"
  mount:
   path: "{{ item.path }}"
   src: "{{ item.src }}"
   state: mounted
   fstype: "{{ item.fstype }}"
  loop: "{{ listmountpartition }}"